### ISSUE TITLE
niuzidada

### ISSUE THREAD

**Issue by NidhoogJX** [wuxia2001/loveyue#34]
![截屏2023-06-05 11 02 51](https://github.com/wuxia2001/loveyue/assets/52187846/bf6460b5-a77d-43fd-af46-8fbde9dc9cf5)
![截屏2023-06-05 11 03 23](https://github.com/wuxia2001/loveyue/assets/52187846/12a4e314-92d3-4fe4-810c-c8c02256dc74)
![截屏2023-06-05 11 06 59](https://github.com/wuxia2001/loveyue/assets/52187846/d0f214ce-32a5-44d8-8b1e-4d5614e34ab0)

**Comment by 1022739387** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
